filebeat.inputs:
- type: filestream
  enabled: true
  parsers:
    - ndjson:
        target: ""
        overwrite_keys: true
        expand_keys: true
        add_error_key: true
  ignore_older: "1h"
  paths:
    - /var/lib/ecs/filebeat/*.json
  publisher_pipeline.disable_host: true

  processors:
    - drop_fields:
        ignore_missing: true
        fields: ["agent.ephemeral_id", "agent.hostname", "agent.name", "agent.id", "agent.type", "agent.version", "ecs.version", "input.type", "process.name", "process.pid", "process.thread.id", "process.thread.name", "log.original", "log.offset", "log.level", "log.origin.function", "log.origin.file.name", "log.origin.file.line", "log.logger", "log.file.path"]

setup.ilm:
  enabled: "true"
  policy_name: logs-shadowserver.log-policy
  rollover_alias: logs-shadowserver.log

setup.template:
  settings:
    index:
      number_of_shards: "1"
      codec: best_compression
  pattern: logs-shadowserver.log-*
  name: logs-shadowserver.log

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["my.elasticsearch.host.com:9200"] # change
  index: logs-shadowserver.log-default

  # Protocol - either `http` (default) or `https`.
  protocol: "https"

  # Authentication credentials - either API key or username/password.
  api_key: "<api_key>" # change
  # username: "elastic"
  # password: "changeme"