name: Deploy Images to CSIRT-RD GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@main
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Image
        run: |
          docker build . --tag ghcr.io/csirt-rd/shadowserver-elastic-ingestor:latest
          docker push ghcr.io/csirt-rd/shadowserver-elastic-ingestor:latest